In [ ]:
import pandas as pd
import altair as alt

# Load the datasets
icrisat_data_url = 'https://raw.githubusercontent.com/Cropdata5320/CropData_Visualizations/main/ICRISAT_cleaned.csv'
food_prices_data_url = 'https://raw.githubusercontent.com/Cropdata5320/CropData_Visualizations/main/Food_Prices_cleaned.csv'

icrisat_data = pd.read_csv(icrisat_data_url)
food_prices_data = pd.read_csv(food_prices_data_url)

In [ ]:
# Ensure the 'commodity' column in food_prices_data is uppercase to match icrisat_crops
food_prices_data['commodity'] = food_prices_data['commodity'].str.upper()

# For the food prices dataset, get the unique commodities.
food_prices_crops = food_prices_data['commodity'].unique().tolist()
food_prices_crops

['RICE',
 'WHEAT',
 'SUGAR',
 'OIL (MUSTARD)',
 'POTATOES',
 'CHICKPEAS',
 'ONIONS',
 'MILK',
 'WHEAT FLOUR',
 'OIL (GROUNDNUT)',
 'OIL (SUNFLOWER)',
 'LENTILS (MASUR)',
 'TOMATOES',
 'OIL (PALM)',
 'SALT (IODISED)',
 'MILK (PASTEURIZED)',
 'TEA (BLACK)',
 'LENTILS',
 'SUGAR (JAGGERY/GUR)',
 'LENTILS (MOONG)',
 'LENTILS (URAD)',
 'OIL (SOYBEAN)',
 'GHEE (VANASPATI)']

In [ ]:
# Make sure the column names in icrisat_data are uppercase
icrisat_data.columns = icrisat_data.columns.str.upper()

# Print out the column names from the ICRISAT dataset
print(icrisat_data.columns)

Index(['DIST CODE', 'YEAR', 'STATE CODE', 'STATE NAME', 'DIST NAME',
       'RICE AREA (1000 HA)', 'RICE PRODUCTION (1000 TONS)',
       'RICE YIELD (KG PER HA)', 'WHEAT AREA (1000 HA)',
       'WHEAT PRODUCTION (1000 TONS)', 'WHEAT YIELD (KG PER HA)',
       'KHARIF SORGHUM AREA (1000 HA)',
       'KHARIF SORGHUM PRODUCTION (1000 TONS)',
       'KHARIF SORGHUM YIELD (KG PER HA)', 'RABI SORGHUM AREA (1000 HA)',
       'RABI SORGHUM PRODUCTION (1000 TONS)', 'RABI SORGHUM YIELD (KG PER HA)',
       'SORGHUM AREA (1000 HA)', 'SORGHUM PRODUCTION (1000 TONS)',
       'SORGHUM YIELD (KG PER HA)', 'PEARL MILLET AREA (1000 HA)',
       'PEARL MILLET PRODUCTION (1000 TONS)', 'PEARL MILLET YIELD (KG PER HA)',
       'MAIZE AREA (1000 HA)', 'MAIZE PRODUCTION (1000 TONS)',
       'MAIZE YIELD (KG PER HA)', 'FINGER MILLET AREA (1000 HA)',
       'FINGER MILLET PRODUCTION (1000 TONS)',
       'FINGER MILLET YIELD (KG PER HA)', 'BARLEY AREA (1000 HA)',
       'BARLEY PRODUCTION (1000 TONS)', 'BARLEY YIELD (KG PER HA)',
       'CHICKPEA AREA (1000 HA)', 'CHICKPEA PRODUCTION (1000 TONS)',
       'CHICKPEA YIELD (KG PER HA)', 'PIGEONPEA AREA (1000 HA)',
       'PIGEONPEA PRODUCTION (1000 TONS)', 'PIGEONPEA YIELD (KG PER HA)',
       'MINOR PULSES AREA (1000 HA)', 'MINOR PULSES PRODUCTION (1000 TONS)',
       'MINOR PULSES YIELD (KG PER HA)', 'GROUNDNUT AREA (1000 HA)',
       'GROUNDNUT PRODUCTION (1000 TONS)', 'GROUNDNUT YIELD (KG PER HA)',
       'SESAMUM AREA (1000 HA)', 'SESAMUM PRODUCTION (1000 TONS)',
       'SESAMUM YIELD (KG PER HA)', 'RAPESEED AND MUSTARD AREA (1000 HA)',
       'RAPESEED AND MUSTARD PRODUCTION (1000 TONS)',
       'RAPESEED AND MUSTARD YIELD (KG PER HA)', 'SAFFLOWER AREA (1000 HA)',
       'SAFFLOWER PRODUCTION (1000 TONS)', 'SAFFLOWER YIELD (KG PER HA)',
       'CASTOR AREA (1000 HA)', 'CASTOR PRODUCTION (1000 TONS)',
       'CASTOR YIELD (KG PER HA)', 'LINSEED AREA (1000 HA)',
       'LINSEED PRODUCTION (1000 TONS)', 'LINSEED YIELD (KG PER HA)',
       'SUNFLOWER AREA (1000 HA)', 'SUNFLOWER PRODUCTION (1000 TONS)',
       'SUNFLOWER YIELD (KG PER HA)', 'SOYABEAN AREA (1000 HA)',
       'SOYABEAN PRODUCTION (1000 TONS)', 'SOYABEAN YIELD (KG PER HA)',
       'OILSEEDS AREA (1000 HA)', 'OILSEEDS PRODUCTION (1000 TONS)',
       'OILSEEDS YIELD (KG PER HA)', 'SUGARCANE AREA (1000 HA)',
       'SUGARCANE PRODUCTION (1000 TONS)', 'SUGARCANE YIELD (KG PER HA)',
       'COTTON AREA (1000 HA)', 'COTTON PRODUCTION (1000 TONS)',
       'COTTON YIELD (KG PER HA)', 'FRUITS AREA (1000 HA)',
       'VEGETABLES AREA (1000 HA)', 'FRUITS AND VEGETABLES AREA (1000 HA)',
       'POTATOES AREA (1000 HA)', 'ONION AREA (1000 HA)',
       'FODDER AREA (1000 HA)'],
      dtype='object')

In [ ]:
# For ICRISAT, we're interested in columns that include "PRODUCTION" as it suggests crop production data.
icrisat_crop_columns = [col for col in icrisat_data.columns if 'PRODUCTION' in col]

# Extract the names of the crops from these columns
# Assuming the format is "CROP PRODUCTION (1000 tons)"
icrisat_crops = [col.split(' ')[0] for col in icrisat_crop_columns]

icrisat_crops

['RICE',
 'WHEAT',
 'KHARIF',
 'RABI',
 'SORGHUM',
 'PEARL',
 'MAIZE',
 'FINGER',
 'BARLEY',
 'CHICKPEA',
 'PIGEONPEA',
 'MINOR',
 'GROUNDNUT',
 'SESAMUM',
 'RAPESEED',
 'SAFFLOWER',
 'CASTOR',
 'LINSEED',
 'SUNFLOWER',
 'SOYABEAN',
 'OILSEEDS',
 'SUGARCANE',
 'COTTON']

In [ ]:
# Normalize the crop names by making them uppercase for a case-insensitive comparison
icrisat_crops = [crop.upper() for crop in icrisat_crops]
food_prices_crops = [crop.upper() for crop in food_prices_crops]

# Find the intersection of these lists to get the common crops
common_crops = list(set(icrisat_crops) & set(food_prices_crops))

common_crops

['WHEAT', 'RICE']

In [ ]:
# For the food prices data, we first need to ensure prices are numeric
food_prices_data['price'] = pd.to_numeric(food_prices_data['price'], errors='coerce')
food_prices_data.head()

,date,Year,state,city,latitude,longitude,category,commodity,unit,priceflag,currency,price,usdprice
0,1994-01-15,1994,Delhi,Delhi,28.666667,77.216667,cereals and tubers,RICE,KG,actual,INR,8.0,0.2550
1,1994-01-15,1994,Delhi,Delhi,28.666667,77.216667,cereals and tubers,WHEAT,KG,actual,INR,5.0,0.1594
2,1994-01-15,1994,Delhi,Delhi,28.666667,77.216667,miscellaneous food,SUGAR,KG,actual,INR,13.5,0.4303
3,1994-01-15,1994,Gujarat,Ahmadabad,23.033333,72.616667,cereals and tubers,RICE,KG,actual,INR,6.8,0.2167
4,1994-01-15,1994,Gujarat,Ahmadabad,23.033333,72.616667,cereals and tubers,WHEAT,KG,actual,INR,6.2,0.1976

In [ ]:
icrisat_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16146 entries, 0 to 16145
Data columns (total 80 columns):
 #   Column                                       Non-Null Count  Dtype
---  ------                                       --------------  -----
 0   DIST CODE                                    16146 non-null  int64
 1   YEAR                                         16146 non-null  int64
 2   STATE CODE                                   16146 non-null  int64
 3   STATE NAME                                   16146 non-null  object
 4   DIST NAME                                    16146 non-null  object
 5   RICE AREA (1000 HA)                          16146 non-null  float64
 6   RICE PRODUCTION (1000 TONS)                  16146 non-null  float64
 7   RICE YIELD (KG PER HA)                       16146 non-null  float64
 8   WHEAT AREA (1000 HA)                         16146 non-null  float64
 9   WHEAT PRODUCTION (1000 TONS)                 16146 non-null  float64
 10  WHEAT YIELD (KG PER HA)                      16146 non-null  float64
 11  KHARIF SORGHUM AREA (1000 HA)                16146 non-null  float64
 12  KHARIF SORGHUM PRODUCTION (1000 TONS)        16146 non-null  float64
 13  KHARIF SORGHUM YIELD (KG PER HA)             16146 non-null  float64
 14  RABI SORGHUM AREA (1000 HA)                  16146 non-null  float64
 15  RABI SORGHUM PRODUCTION (1000 TONS)          16146 non-null  float64
 16  RABI SORGHUM YIELD (KG PER HA)               16146 non-null  float64
 17  SORGHUM AREA (1000 HA)                       16146 non-null  float64
 18  SORGHUM PRODUCTION (1000 TONS)               16146 non-null  float64
 19  SORGHUM YIELD (KG PER HA)                    16146 non-null  float64
 20  PEARL MILLET AREA (1000 HA)                  16146 non-null  float64
 21  PEARL MILLET PRODUCTION (1000 TONS)          16146 non-null  float64
 22  PEARL MILLET YIELD (KG PER HA)               16146 non-null  float64
 23  MAIZE AREA (1000 HA)                         16146 non-null  float64
 24  MAIZE PRODUCTION (1000 TONS)                 16146 non-null  float64
 25  MAIZE YIELD (KG PER HA)                      16146 non-null  float64
 26  FINGER MILLET AREA (1000 HA)                 16146 non-null  float64
 27  FINGER MILLET PRODUCTION (1000 TONS)         16146 non-null  float64
 28  FINGER MILLET YIELD (KG PER HA)              16146 non-null  float64
 29  BARLEY AREA (1000 HA)                        16146 non-null  float64
 30  BARLEY PRODUCTION (1000 TONS)                16146 non-null  float64
 31  BARLEY YIELD (KG PER HA)                     16146 non-null  float64
 32  CHICKPEA AREA (1000 HA)                      16146 non-null  float64
 33  CHICKPEA PRODUCTION (1000 TONS)              16146 non-null  float64
 34  CHICKPEA YIELD (KG PER HA)                   16146 non-null  float64
 35  PIGEONPEA AREA (1000 HA)                     16146 non-null  float64
 36  PIGEONPEA PRODUCTION (1000 TONS)             16146 non-null  float64
 37  PIGEONPEA YIELD (KG PER HA)                  16146 non-null  float64
 38  MINOR PULSES AREA (1000 HA)                  16146 non-null  float64
 39  MINOR PULSES PRODUCTION (1000 TONS)          16146 non-null  float64
 40  MINOR PULSES YIELD (KG PER HA)               16146 non-null  float64
 41  GROUNDNUT AREA (1000 HA)                     16146 non-null  float64
 42  GROUNDNUT PRODUCTION (1000 TONS)             16146 non-null  float64
 43  GROUNDNUT YIELD (KG PER HA)                  16146 non-null  float64
 44  SESAMUM AREA (1000 HA)                       16146 non-null  float64
 45  SESAMUM PRODUCTION (1000 TONS)               16146 non-null  float64
 46  SESAMUM YIELD (KG PER HA)                    16146 non-null  float64
 47  RAPESEED AND MUSTARD AREA (1000 HA)          16146 non-null  float64
 48  RAPESEED AND MUSTARD PRODUCTION (1000 TONS)  16146 non-null  float64
 49  RAPESEED AND MUSTARD YIELD (KG PER HA)       16146 non-null  float64
 50  SAFFLOWER AREA (1000 HA)                     16146 non-null  float64
 51  SAFFLOWER PRODUCTION (1000 TONS)             16146 non-null  float64
 52  SAFFLOWER YIELD (KG PER HA)                  16146 non-null  float64
 53  CASTOR AREA (1000 HA)                        16146 non-null  float64
 54  CASTOR PRODUCTION (1000 TONS)                16146 non-null  float64
 55  CASTOR YIELD (KG PER HA)                     16146 non-null  float64
 56  LINSEED AREA (1000 HA)                       16146 non-null  float64
 57  LINSEED PRODUCTION (1000 TONS)               16146 non-null  float64
 58  LINSEED YIELD (KG PER HA)                    16146 non-null  float64
 59  SUNFLOWER AREA (1000 HA)                     16146 non-null  float64
 60  SUNFLOWER PRODUCTION (1000 TONS)             16146 non-null  float64
 61  SUNFLOWER YIELD (KG PER HA)                  16146 non-null  float64
 62  SOYABEAN AREA (1000 HA)                      16146 non-null  float64
 63  SOYABEAN PRODUCTION (1000 TONS)              16146 non-null  float64
 64  SOYABEAN YIELD (KG PER HA)                   16146 non-null  float64
 65  OILSEEDS AREA (1000 HA)                      16146 non-null  float64
 66  OILSEEDS PRODUCTION (1000 TONS)              16146 non-null  float64
 67  OILSEEDS YIELD (KG PER HA)                   16146 non-null  float64
 68  SUGARCANE AREA (1000 HA)                     16146 non-null  float64
 69  SUGARCANE PRODUCTION (1000 TONS)             16146 non-null  float64
 70  SUGARCANE YIELD (KG PER HA)                  16146 non-null  float64
 71  COTTON AREA (1000 HA)                        16146 non-null  float64
 72  COTTON PRODUCTION (1000 TONS)                16146 non-null  float64
 73  COTTON YIELD (KG PER HA)                     16146 non-null  float64
 74  FRUITS AREA (1000 HA)                        16146 non-null  float64
 75  VEGETABLES AREA (1000 HA)                    16146 non-null  float64
 76  FRUITS AND VEGETABLES AREA (1000 HA)         16146 non-null  float64
 77  POTATOES AREA (1000 HA)                      16146 non-null  float64
 78  ONION AREA (1000 HA)                         16146 non-null  float64
 79  FODDER AREA (1000 HA)                        16146 non-null  float64
dtypes: float64(75), int64(3), object(2)
memory usage: 9.9+ MB

In [ ]:
# Aggregate price data to get average price for each crop and year
average_prices_by_year = food_prices_data.groupby(['Year', 'commodity'])['price'].mean().reset_index()

# Aggregate ICRISAT data to get total production for each crop and year
# For common crop - RICE
rice_production_by_year = icrisat_data.groupby('YEAR')['RICE PRODUCTION (1000 TONS)'].sum().reset_index()

# For common crop - WHEAT
wheat_production_by_year = icrisat_data.groupby('YEAR')['WHEAT PRODUCTION (1000 TONS)'].sum().reset_index()

# Make sure the column names in icrisat_data are uppercase
#food_prices_data.columns = food_prices_data.columns.str.upper()

# Print column names to verify
print("ICRISAT Data Columns:", icrisat_data.columns)
print("Food Prices Data Columns:", food_prices_data.columns)

ICRISAT Data Columns: Index(['DIST CODE', 'YEAR', 'STATE CODE', 'STATE NAME', 'DIST NAME',
       'RICE AREA (1000 HA)', 'RICE PRODUCTION (1000 TONS)',
       'RICE YIELD (KG PER HA)', 'WHEAT AREA (1000 HA)',
       'WHEAT PRODUCTION (1000 TONS)', 'WHEAT YIELD (KG PER HA)',
       'KHARIF SORGHUM AREA (1000 HA)',
       'KHARIF SORGHUM PRODUCTION (1000 TONS)',
       'KHARIF SORGHUM YIELD (KG PER HA)', 'RABI SORGHUM AREA (1000 HA)',
       'RABI SORGHUM PRODUCTION (1000 TONS)', 'RABI SORGHUM YIELD (KG PER HA)',
       'SORGHUM AREA (1000 HA)', 'SORGHUM PRODUCTION (1000 TONS)',
       'SORGHUM YIELD (KG PER HA)', 'PEARL MILLET AREA (1000 HA)',
       'PEARL MILLET PRODUCTION (1000 TONS)', 'PEARL MILLET YIELD (KG PER HA)',
       'MAIZE AREA (1000 HA)', 'MAIZE PRODUCTION (1000 TONS)',
       'MAIZE YIELD (KG PER HA)', 'FINGER MILLET AREA (1000 HA)',
       'FINGER MILLET PRODUCTION (1000 TONS)',
       'FINGER MILLET YIELD (KG PER HA)', 'BARLEY AREA (1000 HA)',
       'BARLEY PRODUCTION (1000 TONS)', 'BARLEY YIELD (KG PER HA)',
       'CHICKPEA AREA (1000 HA)', 'CHICKPEA PRODUCTION (1000 TONS)',
       'CHICKPEA YIELD (KG PER HA)', 'PIGEONPEA AREA (1000 HA)',
       'PIGEONPEA PRODUCTION (1000 TONS)', 'PIGEONPEA YIELD (KG PER HA)',
       'MINOR PULSES AREA (1000 HA)', 'MINOR PULSES PRODUCTION (1000 TONS)',
       'MINOR PULSES YIELD (KG PER HA)', 'GROUNDNUT AREA (1000 HA)',
       'GROUNDNUT PRODUCTION (1000 TONS)', 'GROUNDNUT YIELD (KG PER HA)',
       'SESAMUM AREA (1000 HA)', 'SESAMUM PRODUCTION (1000 TONS)',
       'SESAMUM YIELD (KG PER HA)', 'RAPESEED AND MUSTARD AREA (1000 HA)',
       'RAPESEED AND MUSTARD PRODUCTION (1000 TONS)',
       'RAPESEED AND MUSTARD YIELD (KG PER HA)', 'SAFFLOWER AREA (1000 HA)',
       'SAFFLOWER PRODUCTION (1000 TONS)', 'SAFFLOWER YIELD (KG PER HA)',
       'CASTOR AREA (1000 HA)', 'CASTOR PRODUCTION (1000 TONS)',
       'CASTOR YIELD (KG PER HA)', 'LINSEED AREA (1000 HA)',
       'LINSEED PRODUCTION (1000 TONS)', 'LINSEED YIELD (KG PER HA)',
       'SUNFLOWER AREA (1000 HA)', 'SUNFLOWER PRODUCTION (1000 TONS)',
       'SUNFLOWER YIELD (KG PER HA)', 'SOYABEAN AREA (1000 HA)',
       'SOYABEAN PRODUCTION (1000 TONS)', 'SOYABEAN YIELD (KG PER HA)',
       'OILSEEDS AREA (1000 HA)', 'OILSEEDS PRODUCTION (1000 TONS)',
       'OILSEEDS YIELD (KG PER HA)', 'SUGARCANE AREA (1000 HA)',
       'SUGARCANE PRODUCTION (1000 TONS)', 'SUGARCANE YIELD (KG PER HA)',
       'COTTON AREA (1000 HA)', 'COTTON PRODUCTION (1000 TONS)',
       'COTTON YIELD (KG PER HA)', 'FRUITS AREA (1000 HA)',
       'VEGETABLES AREA (1000 HA)', 'FRUITS AND VEGETABLES AREA (1000 HA)',
       'POTATOES AREA (1000 HA)', 'ONION AREA (1000 HA)',
       'FODDER AREA (1000 HA)'],
      dtype='object')
Food Prices Data Columns: Index(['date', 'Year', 'state', 'city', 'latitude', 'longitude', 'category',
       'commodity', 'unit', 'priceflag', 'currency', 'price', 'usdprice'],
      dtype='object')

In [ ]:
# Aggregate price data to get average price for each crop and year
average_prices_by_year = food_prices_data.groupby(['Year', 'commodity'])['price'].mean().reset_index()

# Aggregate ICRISAT data to get total production for each crop and year
# For common crop - RICE
rice_production_by_year = icrisat_data.groupby('YEAR')['RICE PRODUCTION (1000 TONS)'].sum().reset_index()

# For common crop - WHEAT
wheat_production_by_year = icrisat_data.groupby('YEAR')['WHEAT PRODUCTION (1000 TONS)'].sum().reset_index()

# Merge rice and wheat production data with their respective price data
rice_price_data = pd.merge(rice_production_by_year, average_prices_by_year[average_prices_by_year['commodity'] == 'RICE'],
                           left_on='YEAR', right_on='Year', how='left')
wheat_price_data = pd.merge(wheat_production_by_year, average_prices_by_year[average_prices_by_year['commodity'] == 'WHEAT'],
                            left_on='YEAR', right_on='Year', how='left')

# Drop redundant 'Year' column from rice and wheat data
rice_price_data.drop(columns='Year', inplace=True)
wheat_price_data.drop(columns='Year', inplace=True)

# Now merge these two datasets side by side using 'YEAR' as the key
# Use 'outer' merge to ensure all data is kept and aligned by year
combined_data = pd.merge(rice_price_data, wheat_price_data, on='YEAR', how='inner', suffixes=('_rice', '_wheat'))
#combined_data = pd.concat([rice_price_data, wheat_price_data], axis=1)

# Display the combined data
combined_data

,YEAR,RICE PRODUCTION (1000 TONS),commodity_rice,price_rice,WHEAT PRODUCTION (1000 TONS),commodity_wheat,price_wheat
0,1966,29133.23,NaN,NaN,10989.12,NaN,NaN
1,1967,35056.64,NaN,NaN,16006.30,NaN,NaN
2,1968,34701.52,NaN,NaN,17375.67,NaN,NaN
3,1969,35836.01,NaN,NaN,19232.36,NaN,NaN
4,1970,39324.12,NaN,NaN,22677.88,NaN,NaN
5,1971,39946.79,NaN,NaN,25280.89,NaN,NaN
6,1972,37925.93,NaN,NaN,22879.56,NaN,NaN
7,1973,42026.94,NaN,NaN,20833.39,NaN,NaN
8,1974,37690.51,NaN,NaN,23052.96,NaN,NaN
9,1975,46144.36,NaN,NaN,27150.41,NaN,NaN
10,1976,40226.45,NaN,NaN,27580.73,NaN,NaN
11,1977,50439.41,NaN,NaN,30003.66,NaN,NaN
12,1978,50868.02,NaN,NaN,34078.29,NaN,NaN
13,1979,40560.64,NaN,NaN,30742.00,NaN,NaN
14,1980,52796.25,NaN,NaN,35659.06,NaN,NaN
15,1981,52486.37,NaN,NaN,37154.29,NaN,NaN
16,1982,45081.34,NaN,NaN,42402.18,NaN,NaN
17,1983,57766.50,NaN,NaN,44859.22,NaN,NaN
18,1984,56451.83,NaN,NaN,43846.97,NaN,NaN
19,1985,62289.85,NaN,NaN,46811.09,NaN,NaN
20,1986,58592.01,NaN,NaN,43499.94,NaN,NaN
21,1987,54890.34,NaN,NaN,45504.65,NaN,NaN
22,1988,68923.09,NaN,NaN,53682.89,NaN,NaN
23,1989,73530.86,NaN,NaN,52123.31,NaN,NaN
24,1990,71613.37,NaN,NaN,54449.14,NaN,NaN
25,1991,71858.31,NaN,NaN,55378.51,NaN,NaN
26,1992,70205.91,NaN,NaN,56665.30,NaN,NaN
27,1993,77179.69,NaN,NaN,59400.67,NaN,NaN
28,1994,79273.91,RICE,7.850000,65462.30,WHEAT,5.989109
29,1995,72615.41,RICE,8.119643,61157.13,WHEAT,5.947260
30,1996,78120.14,RICE,8.976590,68631.56,WHEAT,7.398611
31,1997,80504.09,RICE,9.651765,65085.19,WHEAT,8.236972
32,1998,82394.23,RICE,10.124576,70057.41,WHEAT,8.375781
33,1999,86527.07,RICE,11.211921,76209.47,WHEAT,8.446907
34,2000,83476.59,RICE,189.745096,69617.04,WHEAT,217.508214
35,2001,91556.12,RICE,317.054463,72186.10,WHEAT,297.337477
36,2002,69917.86,RICE,185.703950,65404.66,WHEAT,190.052638
37,2003,84971.15,RICE,169.545024,72317.08,WHEAT,200.348883
38,2004,80951.64,RICE,174.053429,69013.36,WHEAT,179.027283
39,2005,87315.59,RICE,195.197867,68379.02,WHEAT,193.111111
40,2006,89984.14,RICE,205.699257,77709.50,WHEAT,271.853356
41,2007,93002.77,RICE,244.269860,80126.73,WHEAT,274.295509
42,2008,95226.84,RICE,284.345072,81613.21,WHEAT,283.248333
43,2009,88070.69,RICE,289.093562,81022.42,WHEAT,314.990514
44,2010,94300.23,RICE,372.582587,93438.55,WHEAT,368.476369
45,2011,102216.27,RICE,204.046023,100269.99,WHEAT,162.861932
46,2012,104237.62,RICE,207.637823,97177.86,WHEAT,165.777570
47,2013,109552.42,RICE,217.750376,102506.18,WHEAT,169.227506
48,2014,112551.62,RICE,233.432631,84866.58,WHEAT,186.828479
49,2015,98820.51,RICE,168.752073,93824.98,WHEAT,143.558390
50,2016,117614.10,RICE,195.177234,112962.82,WHEAT,164.388047
51,2017,114319.61,RICE,225.744603,110418.21,WHEAT,190.711391

In [ ]:
combined_data.isnull().sum()

YEAR                             0
RICE PRODUCTION (1000 TONS)      0
commodity_rice                  28
price_rice                      28
WHEAT PRODUCTION (1000 TONS)     0
commodity_wheat                 28
price_wheat                     28
dtype: int64

In [ ]:
combined_data = combined_data.dropna()
print(combined_data.isnull().sum())
combined_data

YEAR                            0
RICE PRODUCTION (1000 TONS)     0
commodity_rice                  0
price_rice                      0
WHEAT PRODUCTION (1000 TONS)    0
commodity_wheat                 0
price_wheat                     0
dtype: int64

,YEAR,RICE PRODUCTION (1000 TONS),commodity_rice,price_rice,WHEAT PRODUCTION (1000 TONS),commodity_wheat,price_wheat
28,1994,79273.91,RICE,7.850000,65462.30,WHEAT,5.989109
29,1995,72615.41,RICE,8.119643,61157.13,WHEAT,5.947260
30,1996,78120.14,RICE,8.976590,68631.56,WHEAT,7.398611
31,1997,80504.09,RICE,9.651765,65085.19,WHEAT,8.236972
32,1998,82394.23,RICE,10.124576,70057.41,WHEAT,8.375781
33,1999,86527.07,RICE,11.211921,76209.47,WHEAT,8.446907
34,2000,83476.59,RICE,189.745096,69617.04,WHEAT,217.508214
35,2001,91556.12,RICE,317.054463,72186.10,WHEAT,297.337477
36,2002,69917.86,RICE,185.703950,65404.66,WHEAT,190.052638
37,2003,84971.15,RICE,169.545024,72317.08,WHEAT,200.348883
38,2004,80951.64,RICE,174.053429,69013.36,WHEAT,179.027283
39,2005,87315.59,RICE,195.197867,68379.02,WHEAT,193.111111
40,2006,89984.14,RICE,205.699257,77709.50,WHEAT,271.853356
41,2007,93002.77,RICE,244.269860,80126.73,WHEAT,274.295509
42,2008,95226.84,RICE,284.345072,81613.21,WHEAT,283.248333
43,2009,88070.69,RICE,289.093562,81022.42,WHEAT,314.990514
44,2010,94300.23,RICE,372.582587,93438.55,WHEAT,368.476369
45,2011,102216.27,RICE,204.046023,100269.99,WHEAT,162.861932
46,2012,104237.62,RICE,207.637823,97177.86,WHEAT,165.777570
47,2013,109552.42,RICE,217.750376,102506.18,WHEAT,169.227506
48,2014,112551.62,RICE,233.432631,84866.58,WHEAT,186.828479
49,2015,98820.51,RICE,168.752073,93824.98,WHEAT,143.558390
50,2016,117614.10,RICE,195.177234,112962.82,WHEAT,164.388047
51,2017,114319.61,RICE,225.744603,110418.21,WHEAT,190.711391

In [ ]:
# First, let's create a separate DataFrame for rice and wheat
rice_data = combined_data[['YEAR', 'RICE PRODUCTION (1000 TONS)', 'price_rice']].rename(
    columns={'RICE PRODUCTION (1000 TONS)': 'Production', 'price_rice': 'Price'})
rice_data['Commodity'] = 'RICE'

wheat_data = combined_data[['YEAR', 'WHEAT PRODUCTION (1000 TONS)', 'price_wheat']].rename(
    columns={'WHEAT PRODUCTION (1000 TONS)': 'Production', 'price_wheat': 'Price'})
wheat_data['Commodity'] = 'WHEAT'

# Now stack the rice and wheat data on top of each other
long_format = pd.concat([rice_data, wheat_data])

long_format

    YEAR  Production       Price Commodity
28  1994    79273.91    7.850000      RICE
29  1995    72615.41    8.119643      RICE
30  1996    78120.14    8.976590      RICE
31  1997    80504.09    9.651765      RICE
32  1998    82394.23   10.124576      RICE
33  1999    86527.07   11.211921      RICE
34  2000    83476.59  189.745096      RICE
35  2001    91556.12  317.054463      RICE
36  2002    69917.86  185.703950      RICE
37  2003    84971.15  169.545024      RICE
38  2004    80951.64  174.053429      RICE
39  2005    87315.59  195.197867      RICE
40  2006    89984.14  205.699257      RICE
41  2007    93002.77  244.269860      RICE
42  2008    95226.84  284.345072      RICE
43  2009    88070.69  289.093562      RICE
44  2010    94300.23  372.582587      RICE
45  2011   102216.27  204.046023      RICE
46  2012   104237.62  207.637823      RICE
47  2013   109552.42  217.750376      RICE
48  2014   112551.62  233.432631      RICE
49  2015    98820.51  168.752073      RICE
50  2016   117614.10  195.177234      RICE
51  2017   114319.61  225.744603      RICE
28  1994    65462.30    5.989109     WHEAT
29  1995    61157.13    5.947260     WHEAT
30  1996    68631.56    7.398611     WHEAT
31  1997    65085.19    8.236972     WHEAT
32  1998    70057.41    8.375781     WHEAT
33  1999    76209.47    8.446907     WHEAT
34  2000    69617.04  217.508214     WHEAT
35  2001    72186.10  297.337477     WHEAT
36  2002    65404.66  190.052638     WHEAT
37  2003    72317.08  200.348883     WHEAT
38  2004    69013.36  179.027283     WHEAT
39  2005    68379.02  193.111111     WHEAT
40  2006    77709.50  271.853356     WHEAT
41  2007    80126.73  274.295509     WHEAT
42  2008    81613.21  283.248333     WHEAT
43  2009    81022.42  314.990514     WHEAT
44  2010    93438.55  368.476369     WHEAT
45  2011   100269.99  162.861932     WHEAT
46  2012    97177.86  165.777570     WHEAT
47  2013   102506.18  169.227506     WHEAT
48  2014    84866.58  186.828479     WHEAT
49  2015    93824.98  143.558390     WHEAT
50  2016   112962.82  164.388047     WHEAT
51  2017   110418.21  190.711391     WHEAT

In [ ]:

# Define the dropdown selection
input_dropdown = alt.binding_select(options=long_format['Commodity'].unique())
selection = alt.selection_single(fields=['Commodity'], bind=input_dropdown, name='Select_commodity')

# Create the interactive scatter plot with a title
scatter_plot = alt.Chart(long_format).mark_circle(size=60).encode(
    x=alt.X('Production:Q', title='Production Volume (1000 tons)'),
    y=alt.Y('Price:Q', title='Average Price'),
    color=alt.Color('YEAR:N', scale=alt.Scale(scheme='category20'), legend=alt.Legend(title="Year")),
    tooltip=['YEAR:N', 'Commodity:N', 'Production:Q', 'Price:Q']
).add_selection(
    selection
).transform_filter(
    selection
).properties(
    title='Annual Production Volume vs Average Price'  # Adding a title here
)

# To display the chart
scatter_plot

alt.Chart(...)